# https://taskfile.dev

version: '3'

# env:
#   ENV: testing

# dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

vars:
  GREETING: Hello, World!

tasks:
  default:
    deps:
      # - lint
      # - secrets
      - install
      # - run
    cmds:
      # - echo "{{.GREETING}}"
      - ansible-playbook -i inventory -K playbook.yml
    # silent: true

  # run:
  #   cmds:
  #     - ansible-playbook -i inventory -K playbook.yml
  #   interactive: true

  partial:
    cmds:
      - ansible-playbook -i inventory -K playbook.yml --tags={{.CLI_ARGS}}

  lint:
    desc: linting
    deps: [check_lint]
    summary: |
      Lint
    cmds:
      - ansible-lint

  secrets:
    desc: linting
    deps: [check_secret]
    summary: |
      Lint
    cmds:
      - gitleaks detect

  install:
    deps: [check_ansible]
    desc: installl ansible galaxy modules as per requirements.yml
    # summary: |
    #   dependencies
    cmds:
      - ansible-galaxy collection install -r requirements.yml
      - ansible-galaxy install -r requirements.yml

  check_ansible:
    desc: installl ansible galaxy modules as per requirements.yml
    cmds:
      - ansible-galaxy --version

  check_lint:
    desc: installl ansible galaxy modules as per requirements.yml
    cmds:
      - ansible-lint

  check_secret:
    desc: installl ansible galaxy modules as per requirements.yml
    cmds:
      - gitleaks
