---
# TODO: Use sudo once .osx can be run via root with no user interaction.
# - name: Run .osx dotfiles.
#   script: ../files/osx-script.sh --no-restart
#   changed_when: false

- community.general.osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
    state: present
